[package]
name = "rillet"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = "../../README.md"
description = "An actor framework with lock-free reads"

[features]
default = ["im", "smol-str"]
im = ["dep:im"]
smol-str = ["dep:smol_str"]

[[test]]
name = "blessed_types"
required-features = ["im", "smol-str"]

[dependencies]
rillet-macros = { path = "../rillet-macros", version = "0.0.5" }

arc-swap = "1"
event-listener = "5"
smol = "2"
futures-lite = "2"
async-channel = "2"
async-broadcast = "0.7"
futures = "0.3"
im = { version = "15", optional = true }
smol_str = { version = "0.3", optional = true }

[dev-dependencies]
async-io = "2"
